name: ansible-image-build

on:
  schedule:
    - cron: "0 6 * * 0"   
  workflow_dispatch:

jobs:
  ansible_centos_7:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          docker buildx build --push --platform 'linux/amd64,linux/arm64' --builder builder -f ansible/Dockerfile.ansible.centos.7 -t jnix85/ansible:centos.7 .
  ansible_centos_8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          docker buildx build --push --platform 'linux/amd64,linux/arm64' --builder builder -f ansible/Dockerfile.ansible.centos.7 -t jnix85/ansible:centos.stream8 .
  ansible_ubuntu_focal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          docker buildx build --push --platform 'linux/amd64,linux/arm64' --builder builder -f ansible/Dockerfile.ansible.ubuntu.focal -t jnix85/ansible:ubuntu.focal .
  ansible_ubuntu_impish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Build OS
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - name: Install Docker BuildX Plugin
        run: |
          mkdir ${HOME}/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ${HOME}/.docker/cli-plugins/buildx
          chmod +x ${HOME}/.docker/cli-plugins/buildx
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Images
        run: |
          docker buildx create --name builder 
          docker buildx inspect --bootstrap builder
          docker buildx build --push --platform 'linux/amd64,linux/arm64' --builder builder -f ansible/Dockerfile.ansible.ubuntu.impish -t jnix85/ansible:ubuntu.impish .